[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNL NFM"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL NFM"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL NFM"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL NFM"
style = "Bold Italic"

[terminal.shell]
program = "wsl.exe"
args = ["-d", "Ubuntu", "--cd", "~"]

[window]
startup_mode = "Maximized"

[general]
import = ["./catppuccin-frappe.toml"]

[keyboard]
bindings = [{ key = "Slash", mods = "Control", chars = "\u001f" }]
