[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Goto git root"

[[mgr.prepend_keymap]]
on = "<Tab>"
run = ["toggle", "arrow 1"]
desc = "Toggle selected and move down"

[[mgr.prepend_keymap]]
on = "<BackTab>"
run = ["toggle", "arrow -1"]
desc = "Toggle selected and move up"

[[mgr.prepend_keymap]]
on = "<Space>"
run = "spot"
desc = "Spot / file info"
