[opener]
edit = [{ run = '''
if [ -d "$1" ]; then
  cd "$1" && nvim
else
  cd "$(dirname "$1")" && nvim "$(basename "$1")"
fi
''', block = true, for = "unix" }]

[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
url = "*.tar*"
run = 'piper --format=url -- tar tf "$1"'

[[plugin.prepend_previewers]]
url = "*.csv"
run = 'piper -- bat -p --color=always "$1"'

# [[plugin.prepend_previewers]]
# url = "*/"
# run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'
