require("core.lazy")
require("core.diagnostics")
require("core.theme")

require("config.dashboard")
require("config.keymaps")
require("config.buffers")
require("config.options")
require("config.statuscolumn")
require("config.lazygit")
require("config.terminal")
require("config.lsp")
