backend = "glx";
vsync = true;

rules = (
  {
    match = "_PICOM_ANIMATE@ = 1";
    animations = (
      {
        triggers = [ "open", "show" ];
        preset = "slide-in";
        direction = "left";
        duration = 0.20;
      },
      {
        triggers = [ "close", "hide" ];
        preset = "slide-out";
        direction = "right";
        duration = 0.20;
      },
      {
        triggers = [ "geometry" ];
        preset = "geometry-change";
        duration = 0.20;
      }
    );
  }
);
