return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "alejandra",
        "bash-language-server",
        "clangd",
        "cmake-language-server",
        "cmakelang",
        "cmakelint",
        "codelldb",
        "fish-lsp",
        "js-debug-adapter",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "neocmakelsp",
        "nil",
        "prettier",
        "ruff",
        "rust-analyzer",
        "shellcheck",
        "shfmt",
        "statix",
        "stylua",
        "taplo",
        "tree-sitter-cli",
        "verible",
        "vtsls",
        "yaml-language-server",
      },
    },
  },
}
