set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm*:Tc"

set -g focus-events on
set -g mouse on

set -g allow-passthrough on

bind-key & kill-window

set -s command-alias[100] 'ks=kill-session'

bind-key w run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/window.sh switch"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'sainnhe/tmux-fzf'

TMUX_FZF_OPTIONS="-p -w 90% -h 80% -m"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

run-shell -b "bash ~/.config/tmux/statusline.tmux"

if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'