set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm*:Tc"
set -as terminal-features ",xterm-kitty:extkeys"
set -s extended-keys on
set -s extended-keys-format csi-u

set -g focus-events on
set -g mouse on

set -g allow-passthrough on

bind-key & kill-window

set -s command-alias[100] 'ks=kill-session'

bind-key w run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/window.sh switch"

# Use Vi keybindings in copy mode
set-option -g mode-keys vi

# Use Vi keybindings in the command prompt (Prefix + :)
set-option -g status-keys vi

# List of plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-strategy-nvim 'session'

TMUX_FZF_OPTIONS="-p -w 90% -h 80% -m"

run-shell -b "bash ~/.config/tmux/statusline.tmux"

if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
