require("core.lazy")
require("core.diagnostics")
require("core.theme")
require("core.terminal")
require("core.lazygit")
-- require("core.dashboard")
require("core.statuscolumn")
require("core.statusline")
require("core.notifications")
require("core.sessions")
-- require("core.bufferline")
